language: java
jdk:
  - openjdk11
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test -B
services:
  - rabbitmq
after_success:
  - bash <(curl -s https://codecov.io/bash)