version: '3'
services:
  sample-spring-web:
    container_name: sample-spring-web
    build: 
      context: ../sample-spring-web
    ports:
      - "8082:8082"
      - "9082:9082"
    environment:
      DB_URL: jdbc:postgresql://postgresdb:5432/userdb
      DB_USER: dbuser
      DB_PWD: dbpwd
      SAMPLE_REST_SERVICE_URL: http://sample-rest-service:8081/
      AMQP_SERVER_ADDRESS: rabbitmq
      AMQP_SERVER_PORT: 5672
      AMQP_SERVER_USERNAME: guest
      AMQP_SERVER_PASSWORD: guest
    networks:
      - frontend      
      - backend      
networks:
   frontend:
    driver: bridge
   backend:
    driver: bridge