server:
  port: ${PORT:8081}
management:
  server:
    port: ${MANAGEMENT_PORT:9081}
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${DB_USER:dbuser}
    password: ${DB_PWD:dbpwd}
    initialization-mode: never
