management:
  server:
    port: ${MANAGEMENT_PORT:9083}
spring:
  rabbitmq:
    host: ${AMQP_SERVER_ADDRESS:localhost}
    port: ${AMQP_SERVER_PORT:5672}
    username: ${AMQP_SERVER_USERNAME:guest}
    password: ${AMQP_SERVER_PASSWORD:guest}
  mail:
    host: ${SEND_MAIL_HOST:smtp.gmail.com}
    port: ${SEND_MAIL_POST:587}
    username: ${SEND_MAIL_USER:}
    password: ${SEND_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
        starttls:
          enable: true
sampleemail:
  imap: true
  topicExchange: amq.topic
  concurrent: 2
  url: ${SEND_MAIL_INBOX_URL}
  latch: 0
  gotmail:
    queue: sample-gotmail-queue
    routingKey: sample-gotmail.routing.key.#
    pollInterval: 30000
  sendmail:
    queue: sample-sendmail-queue
    routingKey: sample-sendmail.routing.key.#
logging:
  level:
    com.yosanai: DEBUG
